### PR TITLE
Remove EXPRESS features from this gem

### PR DESCRIPTION
**Pull request by w00lf**
metanorma/stepmod-utils#28 Cleaned up SMRL drescription code, removed `-f` option  from ./bin/reverse_adoc

### CODE REVIEW

**Comment by w00lf** [comment]
@ronaldtse do we need to support old `reverse_adoc` `-f` switch for backward compability?

**Comment by ronaldtse** [comment]
I don’t think we need backwards compatibility. Please proceed to merge if this is good to go. Thanks! (Bump version and release gem too)

**Comment by w00lf** [comment]
> I don’t think we need backwards compatibility. Please proceed to merge if this is good to go. Thanks! (Bump version and release gem too)

Released new version - 0.2.10

**Comment by ronaldtse** [comment]
Thanks @w00lf!

**Pull request merged**
