### PR TITLE
Support for ext_descriptions, ext_description and express_ref tags

### PR DESCRIPTION
**Pull request by w00lf**
metanorma/annotated-express#9 support for `ext_descriptions`, `ext_description`, `express_ref` tags

### CODE REVIEW

**Comment by ronaldtse** [comment]
@w00lf we need to handle all tags, including example and note.

They should be:

```
[example]
====
text
====
```

and
```
[NOTE]
--
...
--
```

**Comment by ronaldtse** [comment]
More importantly, I think we need to separate reverseadoc depending on format.

* Normal reverse_adoc is from HTML
* This express XML is clearly not HTML

e.g. we can do `reverseadoc -f smrl-description {filename.xml}` vs `reverseadoc -f html {filename.html}`

**Comment by w00lf** [comment]
> * This express XML is clearly not HTML

The example file you gave me has a number of HTML tags and conversion can be done with just 3 additional converters added. Would not it be unnecessary complication?

**Comment by w00lf** [comment]
> @w00lf we need to handle all tags, including example and note.
> 
> They should be:
> 
> ```
> [example]
> ====
> text
> ====
> ```
> 
> and
> 
> ```
> [NOTE]
> --
> ...
> --
> ```

Thanks, can you also describe what attributes I should support? For example, `example` tag has `number` attribute, how it should be transformed?

**Comment by ronaldtse** [comment]
> The example file you gave me has a number of HTML tags and conversion can be done with just 3 additional converters added. Would not it be unnecessary complication?

No, because normal html should not contain those tags. It would be cleanest to subclass the html converter and add those tags. 

> For example, example tag has number attribute, how it should be transformed?
 
the number attribute can be removed because in Metanorma the numbering is automatic. 

You can find many “descriptions.xml” files for testing in the annotated-express repo :wink:

**Comment by ronaldtse** [comment]
Looks great -- thanks @w00lf !

**Pull request merged**
